# pre-commit is a framework for managing and maintaining multi-language pre-commit hooks.

repos:
  # General Pre-commits Hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: requirements-txt-fixer

  # Auto format the Python code
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
